<a href="https://colab.research.google.com/github/Miyajlove/Assignments/blob/master/spinal_exercises.completed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas dataframe exercises using the sprinter reaction time dataset.  
## Goal: Get familiar with basic dataframe operations

The code block below is a preamble that loads the libraries that we need and sets things up the way we like it.  You can copy and paste this preamble and put it in any notebook to have access to the same libraries.

In [0]:
# Tells the notebooks to view every graph "in line" automatically, rather than requiring a specific `show` command
%matplotlib inline 
# Loads the numpy library (for math stuff)
import numpy as np 
# Load the pandas library (what we use to create, explore, and analyze datasets)
import pandas as pd 
# Loads the matplotlib library (what we use to create graphs)
import matplotlib.pyplot as plt 
# Loads the seaborn library (what we use to create prettier graphs)
import seaborn as sns 
# Sets the default font size for graphs to 150% of its original value (for readability)
sns.set(font_scale=1.5)

#### First we load the original data into a Pandas dataframe called `df`

In [0]:
url = "https://raw.githubusercontent.com/rgerkin/neuro-data-analysis-course/master/data/spinal/2004-2016-Short-Races2.csv"
df = pd.read_csv(url) # Loads the data from that URL into a dataframe
df.head() # Shows the first few rows of that dataframe

,Unnamed: 0,POS,BIB,ATHLETE,COUNTRY,MARK,RxnTime,Race,Round,Gender,Year
0,0,1.0,NaN,Usain BOLT,JAMJAM,10.20 Q,0.186,100 m,Heats,M,2008
1,1,2.0,NaN,Daniel BAILEY,ANTANT,10.24 Q,0.198,100 m,Heats,M,2008
2,2,3.0,NaN,Vicente DE LIMA,BRABRA,10.26 Q,0.168,100 m,Heats,M,2008
3,3,4.0,NaN,Henry VIZCAÍNO,CUBCUB,10.28 q,0.157,100 m,Heats,M,2008
4,4,5.0,NaN,Fabio CERUTTI,ITAITA,10.49,0.136,100 m,Heats,M,2008

#### Now complete the numbered tasks below.  Read the question, then use the code block to fill in your solution

1) A method is just a function that belongs to an object (like a dataframe).  The `.head()` method is a good way to preview the data that you loaded.  Sometimes people work with datasets with thousands or even millions of rows.  You usually don't need to see them all at once!  But sometimes you want to see more than 5 rows.  Try passing an argument to `.head()`, in order to see more rows.  For example, `.head(10)` to see 10 rows.  Or pick some other number.

In [0]:
df.head(10)

,Unnamed: 0,POS,BIB,ATHLETE,COUNTRY,MARK,RxnTime,Race,Round,Gender,Year
0,0,1.0,NaN,Usain BOLT,JAMJAM,10.20 Q,0.186,100 m,Heats,M,2008
1,1,2.0,NaN,Daniel BAILEY,ANTANT,10.24 Q,0.198,100 m,Heats,M,2008
2,2,3.0,NaN,Vicente DE LIMA,BRABRA,10.26 Q,0.168,100 m,Heats,M,2008
3,3,4.0,NaN,Henry VIZCAÍNO,CUBCUB,10.28 q,0.157,100 m,Heats,M,2008
4,4,5.0,NaN,Fabio CERUTTI,ITAITA,10.49,0.136,100 m,Heats,M,2008
5,5,6.0,NaN,Jurgen THEMEN,SURSUR,10.61,0.179,100 m,Heats,M,2008
6,6,7.0,NaN,Moses KAMUT,VANVAN,10.81,0.181,100 m,Heats,M,2008
7,7,8.0,NaN,Francis MANIORU,SOLSOL,11.09,0.197,100 m,Heats,M,2008
8,8,1.0,NaN,Asafa POWELL,JAMJAM,10.16 Q,0.142,100 m,Heats,M,2008
9,9,2.0,NaN,Kim COLLINS,SKNSKN,10.17 Q,0.162,100 m,Heats,M,2008

2) You can also look at the *last* few rows of the data, using the `.tail()` method. Try viewing the last 12 rows of the dataset.

In [0]:
df.tail(12)

,Unnamed: 0,POS,BIB,ATHLETE,COUNTRY,MARK,RxnTime,Race,Round,Gender,Year
2445,2445,3.0,NaN,Taiwo ALADEFA-DARDEN,NGRNGR,13.06,NaN,100 m H,Heats,F,1996
2446,2446,4.0,NaN,Lidiya YURKOVA,BLRBLR,13.2,NaN,100 m H,Heats,F,1996
2447,2447,5.0,NaN,Nadezhda BODROVA,UKRUKR,13.22,NaN,100 m H,Heats,F,1996
2448,2448,6.0,NaN,Rachael ROGERS,FIJFIJ,14.07,NaN,100 m H,Heats,F,1996
2449,2449,NaN,NaN,Elisabeta ANGHEL,ROUROU,DNF,NaN,100 m H,Heats,F,1996
2450,2450,1.0,NaN,Gail DEVERS,USAUSA,12.73,NaN,100 m H,Heats,F,1996
2451,2451,2.0,NaN,Gillian RUSSELL-LOVE,JAMJAM,12.85,NaN,100 m H,Heats,F,1996
2452,2452,3.0,NaN,Yuliya GRAUDYN,RUSRUS,12.95,NaN,100 m H,Heats,F,1996
2453,2453,4.0,NaN,Ime AKPAN,NGRNGR,13.11,NaN,100 m H,Heats,F,1996
2454,2454,5.0,NaN,Olena KRASOVSKA,UKRUKR,13.23,NaN,100 m H,Heats,F,1996
2455,2455,6.0,NaN,Véronique LINSTER,LUXLUX,13.47,NaN,100 m H,Heats,F,1996
2456,2456,NaN,NaN,Carla TUZZI,ITAITA,DNF,NaN,100 m H,Heats,F,1996

3) How much data do you have?  You can find how many rows and columns you have with the `.shape` attribute.  Note the lack of parentheses here.  Attributes differ from methods in that they don't actually do anything (like print out information, or make a plot), but you can access their value to get information about your data.  The `.shape` attribute reports the number of rows and columns of the dataframe.  How many columns does the dataframe have?

In [0]:
df.shape

(2457, 11)

4) Sometimes you only care about one column in your dataframe.  You can access it be name.  For example, `df['ATHLETE']` will access the "ATHLETE" column.  Access the column for reaction time.

In [0]:
df['RxnTime']

0       0.186
1       0.198
2       0.168
3       0.157
4       0.136
5       0.179
6       0.181
7       0.197
8       0.142
9       0.162
10      0.174
11      0.178
12      0.144
13      0.144
14      0.159
15      0.190
16      0.188
17      0.162
18      0.140
19      0.177
20      0.140
21      0.175
22      0.123
23      0.152
24      0.156
25      0.141
26      0.139
27      0.160
28      0.184
29      0.171
        ...
2427      NaN
2428      NaN
2429      NaN
2430      NaN
2431      NaN
2432      NaN
2433      NaN
2434      NaN
2435      NaN
2436      NaN
2437      NaN
2438      NaN
2439      NaN
2440      NaN
2441      NaN
2442      NaN
2443      NaN
2444      NaN
2445      NaN
2446      NaN
2447      NaN
2448      NaN
2449      NaN
2450      NaN
2451      NaN
2452      NaN
2453      NaN
2454      NaN
2455      NaN
2456      NaN
Name: RxnTime, Length: 2457, dtype: float64

5) Notice that the above doesn't look like a dataframe anymore.  That's because you've only accessed one column, so the two-dimensional dataset (rows x columns) is now only one-dimensional. One-dimensional data in Pandas is convered into a so-called "Series".  Many of the same methods that belong to dataframes also belong to a series, e.g. `.head()` or `.mean()`.  Find the median reaction time as you did in the earlier homework assignment, but operating directly on the series containing the reaction times.

In [0]:
df['RxnTime'].median()

0.165

6) Sometimes you want to keep a dataframe, but just with fewer columns.  For example, only the name and reaction time.  You do this with an extra set of brackets, i.e. `df[['col1','col2']]` if you wanted to access hypothetical columns named 'col1' and 'col2'.  Try generating a dataframe that has only the name and reaction time columns from the original dataset.

In [0]:
df[['ATHLETE','RxnTime']]

                          ATHLETE  RxnTime
0                      Usain BOLT    0.186
1                   Daniel BAILEY    0.198
2                 Vicente DE LIMA    0.168
3                  Henry VIZCAÍNO    0.157
4                   Fabio CERUTTI    0.136
5                   Jurgen THEMEN    0.179
6                     Moses KAMUT    0.181
7                 Francis MANIORU    0.197
8                    Asafa POWELL    0.142
9                     Kim COLLINS    0.162
10                Craig PICKERING    0.174
11                  Daniel GRUESO    0.178
12                    Dariusz KUC    0.144
13          Berenger Aymard BOSSE    0.144
14                     Aisea TOHI    0.159
15                    Roman CRESS    0.190
16               Richard THOMPSON    0.188
17              Martial MBANDJOCK    0.162
18                  Simone COLLIO    0.140
19                    Aziz ZAKARI    0.177
20                   Andrew HINDS    0.140
21             Suryo Agung WIBOWO    0.175
22                    Jared LEWIS    0.123
23                Rabangaki NAWAI    0.152
24                 Michael FRATER    0.156
25                  Pierre BROWNE    0.141
26                   Darrel BROWN    0.139
27               Nobuharu ASAHARA    0.160
28                Holder DA SILVA    0.184
29                  Idrissa SANOU    0.171
...                           ...      ...
2427               Lesley TASHLIN      NaN
2428             Ludmila ENGQUIST      NaN
2429                 Angela ATEDE      NaN
2430        María José MARDOMINGO      NaN
2431  Monique ÉWANJÉ-ÉPÉE TOURRET      NaN
2432           Lena SOLLI-REIMANN      NaN
2433           Natalya GRIGORYEVA      NaN
2434               Sonia PAQUETTE      NaN
2435                Julie BAUMANN      NaN
2436                 Angela THORP      NaN
2437          Lynda TOLBERT-GOODE      NaN
2438             Kristin PATZWAHL      NaN
2439         Tatyana RESHETNIKOVA      NaN
2440                Cécile CINÉLU      NaN
2441                Bich Huong VU      NaN
2442               Aminata CAMARA      NaN
2443              Brigita BUKOVEC      NaN
2444           Dionne ROSE-HENLEY      NaN
2445         Taiwo ALADEFA-DARDEN      NaN
2446               Lidiya YURKOVA      NaN
2447             Nadezhda BODROVA      NaN
2448               Rachael ROGERS      NaN
2449             Elisabeta ANGHEL      NaN
2450                  Gail DEVERS      NaN
2451         Gillian RUSSELL-LOVE      NaN
2452               Yuliya GRAUDYN      NaN
2453                    Ime AKPAN      NaN
2454              Olena KRASOVSKA      NaN
2455            Véronique LINSTER      NaN
2456                  Carla TUZZI      NaN

[2457 rows x 2 columns]

7) Columns have names ('ATHLETE', 'COUNTRY', etc.), but so do rows.  The row names are part of the so-called "index" of the dataframe (or series), and allow you to access data more intuitively than just by row number.  In this case though, the names in the index are the row numbers.  You can extract row 144 with `df.loc[144]`.  Note the use of the `.loc` attribute, and the brackets instead of parentheses.  Use this extract the row containing Usain Bolt's 2008 preliminary heats data (hint, it is at the beginning of the dataframe).

In [0]:
df.loc[0]

Unnamed: 0             0
POS                    1
BIB                  NaN
ATHLETE       Usain BOLT
COUNTRY           JAMJAM
MARK             10.20 Q
RxnTime            0.186
Race               100 m
Round              Heats
Gender                 M
Year                2008
Name: 0, dtype: object

8) You can access specific cells of the dataframe by row and column using `.loc`, e.g. `df.loc[7,'Country']`.  You can also edit data the same way.  Maybe Usain Bolt's preliminary heats time was faster than reported, say 9.5 seconds?  Edit the dataframe with `.loc` to make that change.  Be sure to use the `=` sign or you won't actually make the change!

In [0]:
df.loc[0,'MARK']=9.5

9) I don't like the way this data is organized.  Accessing it by arbitrary row numbers is not intuitive at all.  Let's organize the data by athlete name and year instead, using the `set_index()` method.  Inside the parentheses, put a list containing the column name indicating athlete name and the column name indicating the year.  Don't forget quotes and brackets!

In [0]:
df.set_index(['ATHLETE','Year'])

,,Unnamed: 0,POS,BIB,COUNTRY,MARK,RxnTime,Race,Round,Gender
ATHLETE,Year,,,,,,,,,
Usain BOLT,2008,0,1.0,NaN,JAMJAM,9.5,0.186,100 m,Heats,M
Daniel BAILEY,2008,1,2.0,NaN,ANTANT,10.24 Q,0.198,100 m,Heats,M
Vicente DE LIMA,2008,2,3.0,NaN,BRABRA,10.26 Q,0.168,100 m,Heats,M
Henry VIZCAÍNO,2008,3,4.0,NaN,CUBCUB,10.28 q,0.157,100 m,Heats,M
Fabio CERUTTI,2008,4,5.0,NaN,ITAITA,10.49,0.136,100 m,Heats,M
Jurgen THEMEN,2008,5,6.0,NaN,SURSUR,10.61,0.179,100 m,Heats,M
Moses KAMUT,2008,6,7.0,NaN,VANVAN,10.81,0.181,100 m,Heats,M
Francis MANIORU,2008,7,8.0,NaN,SOLSOL,11.09,0.197,100 m,Heats,M
Asafa POWELL,2008,8,1.0,NaN,JAMJAM,10.16 Q,0.142,100 m,Heats,M
Kim COLLINS,2008,9,2.0,NaN,SKNSKN,10.17 Q,0.162,100 m,Heats,M
Craig PICKERING,2008,10,3.0,NaN,GBRGBR,10.21 Q,0.174,100 m,Heats,M
Daniel GRUESO,2008,11,4.0,NaN,COLCOL,10.35 q,0.178,100 m,Heats,M
Dariusz KUC,2008,12,5.0,NaN,POLPOL,10.44 q,0.144,100 m,Heats,M
Berenger Aymard BOSSE,2008,13,6.0,NaN,CAFCAF,10.51,0.144,100 m,Heats,M
Aisea TOHI,2008,14,7.0,NaN,TGATGA,11.17,0.159,100 m,Heats,M
Roman CRESS,2008,15,8.0,NaN,MHLMHL,11.18,0.190,100 m,Heats,M
Richard THOMPSON,2008,16,1.0,NaN,TTOTTO,10.24 Q,0.188,100 m,Heats,M
Martial MBANDJOCK,2008,17,2.0,NaN,FRAFRA,10.26 Q,0.162,100 m,Heats,M
Simone COLLIO,2008,18,3.0,NaN,ITAITA,10.32 Q,0.140,100 m,Heats,M
Aziz ZAKARI,2008,19,4.0,NaN,GHAGHA,10.34 q,0.177,100 m,Heats,M
Andrew HINDS,2008,20,5.0,NaN,BARBAR,10.35 q,0.140,100 m,Heats,M
Suryo Agung WIBOWO,2008,21,6.0,NaN,INAINA,10.46,0.175,100 m,Heats,M
Jared LEWIS,2008,22,7.0,NaN,VINVIN,11,0.123,100 m,Heats,M
Rabangaki NAWAI,2008,23,8.0,NaN,KIRKIR,11.29,0.152,100 m,Heats,M
Michael FRATER,2008,24,1.0,NaN,JAMJAM,10.15 Q,0.156,100 m,Heats,M
Pierre BROWNE,2008,25,2.0,NaN,CANCAN,10.22 Q,0.141,100 m,Heats,M
Darrel BROWN,2008,26,3.0,NaN,TTOTTO,10.22 Q,0.139,100 m,Heats,M
Nobuharu ASAHARA,2008,27,4.0,NaN,JPNJPN,10.25 q,0.160,100 m,Heats,M
Holder DA SILVA,2008,28,5.0,NaN,GBSGBS,10.58,0.184,100 m,Heats,M
Idrissa SANOU,2008,29,6.0,NaN,BURBUR,10.63,0.171,100 m,Heats,M
...,...,...,...,...,...,...,...,...,...,...
Lesley TASHLIN,1996,2427,7.0,NaN,CANCAN,13.61,NaN,100 m H,Heats,F
Ludmila ENGQUIST,1996,2428,1.0,NaN,SWESWE,12.66,NaN,100 m H,Heats,F
Angela ATEDE,1996,2429,2.0,NaN,NGRNGR,12.88,NaN,100 m H,Heats,F
María José MARDOMINGO,1996,2430,3.0,NaN,ESPESP,12.91,NaN,100 m H,Heats,F
Monique ÉWANJÉ-ÉPÉE TOURRET,1996,2431,4.0,NaN,FRAFRA,13.12,NaN,100 m H,Heats,F
Lena SOLLI-REIMANN,1996,2432,5.0,NaN,NORNOR,13.13,NaN,100 m H,Heats,F
Natalya GRIGORYEVA,1996,2433,6.0,NaN,UKRUKR,13.16,NaN,100 m H,Heats,F
Sonia PAQUETTE,1996,2434,7.0,NaN,CANCAN,13.29,NaN,100 m H,Heats,F
Julie BAUMANN,1996,2435,1.0,NaN,SUISUI,12.86,NaN,100 m H,Heats,F
Angela THORP,1996,2436,2.0,NaN,GBRGBR,12.93,NaN,100 m H,Heats,F
Lynda TOLBERT-GOODE,1996,2437,3.0,NaN,USAUSA,12.97,NaN,100 m H,Heats,F
Kristin PATZWAHL,1996,2438,4.0,NaN,GERGER,12.98,NaN,100 m H,Heats,F
Tatyana RESHETNIKOVA,1996,2439,5.0,NaN,RUSRUS,13.01,NaN,100 m H,Heats,F
Cécile CINÉLU,1996,2440,6.0,NaN,FRAFRA,13.05,NaN,100 m H,Heats,F
Bich Huong VU,1996,2441,7.0,NaN,VIEVIE,13.85,NaN,100 m H,Heats,F
Aminata CAMARA,1996,2442,8.0,NaN,MLIMLI,14.94,NaN,100 m H,Heats,F
Brigita BUKOVEC,1996,2443,1.0,NaN,SLOSLO,12.72,NaN,100 m H,Heats,F
Dionne ROSE-HENLEY,1996,2444,2.0,NaN,JAMJAM,12.81,NaN,100 m H,Heats,F
Taiwo ALADEFA-DARDEN,1996,2445,3.0,NaN,NGRNGR,13.06,NaN,100 m H,Heats,F
Lidiya YURKOVA,1996,2446,4.0,NaN,BLRBLR,13.2,NaN,100 m H,Heats,F
Nadezhda BODROVA,1996,2447,5.0,NaN,UKRUKR,13.22,NaN,100 m H,Heats,F
Rachael ROGERS,1996,2448,6.0,NaN,FIJFIJ,14.07,NaN,100 m H,Heats,F
Elisabeta ANGHEL,1996,2449,NaN,NaN,ROUROU,DNF,NaN,100 m H,Heats,F
Gail DEVERS,1996,2450,1.0,NaN,USAUSA,12.73,NaN,100 m H,Heats,F
Gillian RUSSELL-LOVE,1996,2451,2.0,NaN,JAMJAM,12.85,NaN,100 m H,Heats,F
Yuliya GRAUDYN,1996,2452,3.0,NaN,RUSRUS,12.95,NaN,100 m H,Heats,F
Ime AKPAN,1996,2453,4.0,NaN,NGRNGR,13.11,NaN,100 m H,Heats,F
Olena KRASOVSKA,1996,2454,5.0,NaN,UKRUKR,13.23,NaN,100 m H,Heats,F
Véronique LINSTER,1996,2455,6.0,NaN,LUXLUX,13.47,NaN,100 m H,Heats,F
Carla TUZZI,1996,2456,NaN,NaN,ITAITA,DNF,NaN,100 m H,Heats,F

10) That's OK, but it doesn't look much nicer.  Maybe if it the index was sorted?  If you've ever done a hierarchical sort in Excel, this will be similar.  Try the same command as above, but append `.sort_index()`  to it

In [0]:
df.set_index(['ATHLETE','Year']).sort_index()

                                Unnamed: 0  POS     BIB COUNTRY        MARK  \
ATHLETE                   Year
Aaron BROWN               2016        1147  3.0  2192.0  CANCAN       10.24
Abdul GHAFOOR             1996        2257  8.0     NaN  AFGAFG        12.2
Abdul RASHID              2008         378  8.0     NaN  PAKPAK       14.52
Abdul Wahab ZAHIRI        2016        1068  7.0  2000.0  AFGAFG       11.56
Abdullah AL-SOOLI         2008          44  5.0     NaN  OMAOMA       10.53
Abdullah Abkar MOHAMMED   2016        1106  5.0  2717.0  KSAKSA       10.26
Abiodun OYEPITAN          2004        1316  2.0     NaN  GBRGBR     11.23 Q
                          2004        1324  3.0     NaN  GBRGBR     11.28 Q
                          2004        1358  5.0     NaN  GBRGBR       11.18
                          2012         509  5.0  1869.0  GBRGBR     11.22 q
                          2012         551  7.0  1869.0  GBRGBR       11.36
Abraham KEPSIN            2000        1772  8.0     NaN  VANVAN       11.12
Adam GEMILI               2012         639  2.0  1809.0  GBRGBR     10.11 Q
                          2012         679  2.0  1809.0  GBRGBR       10.06
Adrian DURANT             2004        1417  6.0     NaN  ISVISV       10.52
Adrian GRIFFITH           2016        1091  8.0  2067.0  BAHBAH       10.53
Adrian WOODLEY            2000        2037  4.0     NaN  CANCAN     13.71 Q
                          2000        2064  6.0     NaN  CANCAN       14.04
Adrien DEGHELT            2012         778  3.0  1136.0  BELBEL     13.52 Q
                          2012         832  4.0  1136.0  BELBEL       13.42
Afa ISMAIL                2012         460  5.0  2494.0  MDVMDV       12.52
Affoué Amandine ALLOU     2004        1278  4.0     NaN  CIVCIV       11.46
                          2008         174  5.0     NaN  CIVCIV       11.75
Agné EGGERTH              2000        1894  6.0     NaN  LTULTU       11.87
                          2004        1302  4.0     NaN  LTULTU       11.44
Ahmad HAZER               2012         810  9.0  2421.0  LBNLBN       14.82
                          2016        1208  7.0  2731.0  LIBLIB        15.5
Ahmed DOUHOU              1996        2317  5.0     NaN  CIVCIV       10.53
Aisea TOHI                2008          14  7.0     NaN  TGATGA       11.17
Aissata TOURÉ             2012         462  7.0  2021.0  GUIGUI       13.25
...                                    ...  ...     ...     ...         ...
Yuniel HERNÁNDEZ          2004        1683  NaN     NaN  CUBCUB         DNS
Yuriy ARISTOV             1996        2364  8.0     NaN  UZBUZB       15.04
Yvette LEWIS              2016         933  8.0  1081.0  PANPAN       13.35
Yvonne KANAZAWA           1996        2425  5.0     NaN  JPNJPN        13.3
                          2000        2110  5.0     NaN  JPNJPN     13.13 q
                          2000        2150  6.0     NaN  JPNJPN     13.11 q
                          2000        2176  8.0     NaN  JPNJPN       13.16
Zaidatul Husniah ZULKIFLI 2016         960  3.0   999.0  MASMAS     12.12 q
                          2016        1029  8.0   999.0  MASMAS       12.62
Zhanna BLOCK              1996        2192  1.0     NaN  UKRUKR        11.2
                          2000        1873  1.0     NaN  UKRUKR     11.27 Q
                          2000        1956  1.0     NaN  UKRUKR     11.08 Q
                          2000        1974  3.0     NaN  UKRUKR     11.32 Q
                          2000        1991  4.0     NaN  UKRUKR        11.2
                          2004        1306  NaN     NaN  UKRUKR          DQ
                          2004        1337  NaN     NaN  UKRUKR          DQ
                          2004        1369  NaN     NaN  UKRUKR          DQ
Zhenye XIE                2016        1102  1.0  2234.0  CHNCHN     10.08 Q
                          2016        1160  7.0  2234.0  CHNCHN       10.11
Zhivko VIDENOV            2000        2018  NaN     NaN  BULBUL         DNF
Zlatka GEORGIEVA          1996        2188  4.0     NaN  BULBUL       11.74
Ággelos PAVLAKÁKIS        2000        1745  NaN     NaN  GREGRE         DNS
Ángel David RODRÍGUEZ     2008          35  4.0     NaN  ESPESP     10.34 q
                          2008         111  8.0     NaN  ESPESP       10.35
                          2012         609  4.0  1636.0  ESPESP       10.34
Ángela TENORIO            2016         984  3.0   613.0  ECUECU     11.35 q
                          2016        1034  5.0   613.0  ECUECU       11.14
Éder Antonio SOUZA        2016        1213  4.0  2154.0  BRABRA     13.61 Q
                          2016        1250  NaN  2154.0  BRABRA  DQ R 168.7
Édson RIBEIRO             1996        2272  5.0     NaN  BRABRA       10.39

                                RxnTime     Race        Round Gender
ATHLETE                   Year
Aaron BROWN               2016    0.135    100 m        Heats      M
Abdul GHAFOOR             1996      NaN    100 m        Heats      M
Abdul RASHID              2008    0.172  110 m H        Heats      M
Abdul Wahab ZAHIRI        2016    0.170    100 m  Preliminary      M
Abdullah AL-SOOLI         2008    0.153    100 m        Heats      M
Abdullah Abkar MOHAMMED   2016    0.154    100 m        Heats      M
Abiodun OYEPITAN          2004    0.181    100 m        Heats      F
                          2004    0.198    100 m      Quarter      F
                          2004    0.140    100 m         Semi      F
                          2012    0.153    100 m        Heats      F
                          2012    0.151    100 m         Semi      F
Abraham KEPSIN            2000    0.172    100 m        Heats      M
Adam GEMILI               2012    0.156    100 m        Heats      M
                          2012    0.158    100 m         Semi      M
Adrian DURANT             2004    0.223    100 m        Heats      M
Adrian GRIFFITH           2016    0.143    100 m        Heats      M
Adrian WOODLEY            2000    0.175  110 m H        Heats      M
                          2000    0.178  110 m H      Quarter      M
Adrien DEGHELT            2012    0.158  110 m H        Heats      M
                          2012    0.142  110 m H         Semi      M
Afa ISMAIL                2012    0.223    100 m  Preliminary      F
Affoué Amandine ALLOU     2004    0.182    100 m        Heats      F
                          2008    0.204    100 m        Heats      F
Agné EGGERTH              2000    0.277    100 m        Heats      F
                          2004    0.177    100 m        Heats      F
Ahmad HAZER               2012    0.195  110 m H        Heats      M
                          2016    0.144  110 m H        Heats      M
Ahmed DOUHOU              1996      NaN    100 m        Heats      M
Aisea TOHI                2008    0.159    100 m        Heats      M
Aissata TOURÉ             2012    0.198    100 m  Preliminary      F
...                                 ...      ...          ...    ...
Yuniel HERNÁNDEZ          2004      NaN  110 m H         Semi      M
Yuriy ARISTOV             1996      NaN  110 m H        Heats      M
Yvette LEWIS              2016    0.150  100 m H        Heats      F
Yvonne KANAZAWA           1996      NaN  100 m H        Heats      F
                          2000    0.192  100 m H        Heats      F
                          2000    0.184  100 m H      Quarter      F
                          2000      NaN  100 m H         Semi      F
Zaidatul Husniah ZULKIFLI 2016    0.151    100 m  Preliminary      F
                          2016    0.149    100 m        Heats      F
Zhanna BLOCK              1996      NaN    100 m        Heats      F
                          2000    0.215    100 m        Heats      F
                          2000    0.191    100 m      Quarter      F
                          2000    0.227    100 m         Semi      F
                          2000    0.223    100 m        Final      F
                          2004    0.186    100 m        Heats      F
                          2004    0.203    100 m      Quarter      F
                          2004    0.158    100 m         Semi      F
Zhenye XIE                2016    0.143    100 m        Heats      M
                          2016    0.134    100 m         Semi      M
Zhivko VIDENOV            2000    0.122  110 m H        Heats      M
Zlatka GEORGIEVA          1996      NaN    100 m        Heats      F
Ággelos PAVLAKÁKIS        2000      NaN    100 m        Heats      M
Ángel David RODRÍGUEZ     2008    0.145    100 m        Heats      M
                          2008    0.154    100 m      Quarter      M
                          2012    0.168    100 m        Heats      M
Ángela TENORIO            2016    0.150    100 m        Heats      F
                          2016    0.145    100 m         Semi      F
Éder Antonio SOUZA        2016    0.134  110 m H        Heats      M
                          2016    0.137  110 m H         Semi      M
Édson RIBEIRO             1996      NaN    100 m        Heats      M

[2457 rows x 9 columns]

11) Display the dataframe again by entering `df` on an empty line (e.g. in the code cell below, or create a new code cell).  Does it reflect the changes you made above?  If not, it's because `.set_index()`, `.sort_index()` (and most other methods) only return modified copies of your data; they don't overwrite it.  If you want to work with that modified copy, set the original dataframe equal to it, i.e. `df = ...` where `...` would contain the command you used above.

In [0]:
df

,Unnamed: 0,POS,BIB,ATHLETE,COUNTRY,MARK,RxnTime,Race,Round,Gender,Year
0,0,1.0,NaN,Usain BOLT,JAMJAM,9.5,0.186,100 m,Heats,M,2008
1,1,2.0,NaN,Daniel BAILEY,ANTANT,10.24 Q,0.198,100 m,Heats,M,2008
2,2,3.0,NaN,Vicente DE LIMA,BRABRA,10.26 Q,0.168,100 m,Heats,M,2008
3,3,4.0,NaN,Henry VIZCAÍNO,CUBCUB,10.28 q,0.157,100 m,Heats,M,2008
4,4,5.0,NaN,Fabio CERUTTI,ITAITA,10.49,0.136,100 m,Heats,M,2008
5,5,6.0,NaN,Jurgen THEMEN,SURSUR,10.61,0.179,100 m,Heats,M,2008
6,6,7.0,NaN,Moses KAMUT,VANVAN,10.81,0.181,100 m,Heats,M,2008
7,7,8.0,NaN,Francis MANIORU,SOLSOL,11.09,0.197,100 m,Heats,M,2008
8,8,1.0,NaN,Asafa POWELL,JAMJAM,10.16 Q,0.142,100 m,Heats,M,2008
9,9,2.0,NaN,Kim COLLINS,SKNSKN,10.17 Q,0.162,100 m,Heats,M,2008
10,10,3.0,NaN,Craig PICKERING,GBRGBR,10.21 Q,0.174,100 m,Heats,M,2008
11,11,4.0,NaN,Daniel GRUESO,COLCOL,10.35 q,0.178,100 m,Heats,M,2008
12,12,5.0,NaN,Dariusz KUC,POLPOL,10.44 q,0.144,100 m,Heats,M,2008
13,13,6.0,NaN,Berenger Aymard BOSSE,CAFCAF,10.51,0.144,100 m,Heats,M,2008
14,14,7.0,NaN,Aisea TOHI,TGATGA,11.17,0.159,100 m,Heats,M,2008
15,15,8.0,NaN,Roman CRESS,MHLMHL,11.18,0.190,100 m,Heats,M,2008
16,16,1.0,NaN,Richard THOMPSON,TTOTTO,10.24 Q,0.188,100 m,Heats,M,2008
17,17,2.0,NaN,Martial MBANDJOCK,FRAFRA,10.26 Q,0.162,100 m,Heats,M,2008
18,18,3.0,NaN,Simone COLLIO,ITAITA,10.32 Q,0.140,100 m,Heats,M,2008
19,19,4.0,NaN,Aziz ZAKARI,GHAGHA,10.34 q,0.177,100 m,Heats,M,2008
20,20,5.0,NaN,Andrew HINDS,BARBAR,10.35 q,0.140,100 m,Heats,M,2008
21,21,6.0,NaN,Suryo Agung WIBOWO,INAINA,10.46,0.175,100 m,Heats,M,2008
22,22,7.0,NaN,Jared LEWIS,VINVIN,11,0.123,100 m,Heats,M,2008
23,23,8.0,NaN,Rabangaki NAWAI,KIRKIR,11.29,0.152,100 m,Heats,M,2008
24,24,1.0,NaN,Michael FRATER,JAMJAM,10.15 Q,0.156,100 m,Heats,M,2008
25,25,2.0,NaN,Pierre BROWNE,CANCAN,10.22 Q,0.141,100 m,Heats,M,2008
26,26,3.0,NaN,Darrel BROWN,TTOTTO,10.22 Q,0.139,100 m,Heats,M,2008
27,27,4.0,NaN,Nobuharu ASAHARA,JPNJPN,10.25 q,0.160,100 m,Heats,M,2008
28,28,5.0,NaN,Holder DA SILVA,GBSGBS,10.58,0.184,100 m,Heats,M,2008
29,29,6.0,NaN,Idrissa SANOU,BURBUR,10.63,0.171,100 m,Heats,M,2008
...,...,...,...,...,...,...,...,...,...,...,...
2427,2427,7.0,NaN,Lesley TASHLIN,CANCAN,13.61,NaN,100 m H,Heats,F,1996
2428,2428,1.0,NaN,Ludmila ENGQUIST,SWESWE,12.66,NaN,100 m H,Heats,F,1996
2429,2429,2.0,NaN,Angela ATEDE,NGRNGR,12.88,NaN,100 m H,Heats,F,1996
2430,2430,3.0,NaN,María José MARDOMINGO,ESPESP,12.91,NaN,100 m H,Heats,F,1996
2431,2431,4.0,NaN,Monique ÉWANJÉ-ÉPÉE TOURRET,FRAFRA,13.12,NaN,100 m H,Heats,F,1996
2432,2432,5.0,NaN,Lena SOLLI-REIMANN,NORNOR,13.13,NaN,100 m H,Heats,F,1996
2433,2433,6.0,NaN,Natalya GRIGORYEVA,UKRUKR,13.16,NaN,100 m H,Heats,F,1996
2434,2434,7.0,NaN,Sonia PAQUETTE,CANCAN,13.29,NaN,100 m H,Heats,F,1996
2435,2435,1.0,NaN,Julie BAUMANN,SUISUI,12.86,NaN,100 m H,Heats,F,1996
2436,2436,2.0,NaN,Angela THORP,GBRGBR,12.93,NaN,100 m H,Heats,F,1996
2437,2437,3.0,NaN,Lynda TOLBERT-GOODE,USAUSA,12.97,NaN,100 m H,Heats,F,1996
2438,2438,4.0,NaN,Kristin PATZWAHL,GERGER,12.98,NaN,100 m H,Heats,F,1996
2439,2439,5.0,NaN,Tatyana RESHETNIKOVA,RUSRUS,13.01,NaN,100 m H,Heats,F,1996
2440,2440,6.0,NaN,Cécile CINÉLU,FRAFRA,13.05,NaN,100 m H,Heats,F,1996
2441,2441,7.0,NaN,Bich Huong VU,VIEVIE,13.85,NaN,100 m H,Heats,F,1996
2442,2442,8.0,NaN,Aminata CAMARA,MLIMLI,14.94,NaN,100 m H,Heats,F,1996
2443,2443,1.0,NaN,Brigita BUKOVEC,SLOSLO,12.72,NaN,100 m H,Heats,F,1996
2444,2444,2.0,NaN,Dionne ROSE-HENLEY,JAMJAM,12.81,NaN,100 m H,Heats,F,1996
2445,2445,3.0,NaN,Taiwo ALADEFA-DARDEN,NGRNGR,13.06,NaN,100 m H,Heats,F,1996
2446,2446,4.0,NaN,Lidiya YURKOVA,BLRBLR,13.2,NaN,100 m H,Heats,F,1996
2447,2447,5.0,NaN,Nadezhda BODROVA,UKRUKR,13.22,NaN,100 m H,Heats,F,1996
2448,2448,6.0,NaN,Rachael ROGERS,FIJFIJ,14.07,NaN,100 m H,Heats,F,1996
2449,2449,NaN,NaN,Elisabeta ANGHEL,ROUROU,DNF,NaN,100 m H,Heats,F,1996
2450,2450,1.0,NaN,Gail DEVERS,USAUSA,12.73,NaN,100 m H,Heats,F,1996
2451,2451,2.0,NaN,Gillian RUSSELL-LOVE,JAMJAM,12.85,NaN,100 m H,Heats,F,1996
2452,2452,3.0,NaN,Yuliya GRAUDYN,RUSRUS,12.95,NaN,100 m H,Heats,F,1996
2453,2453,4.0,NaN,Ime AKPAN,NGRNGR,13.11,NaN,100 m H,Heats,F,1996
2454,2454,5.0,NaN,Olena KRASOVSKA,UKRUKR,13.23,NaN,100 m H,Heats,F,1996
2455,2455,6.0,NaN,Véronique LINSTER,LUXLUX,13.47,NaN,100 m H,Heats,F,1996
2456,2456,NaN,NaN,Carla TUZZI,ITAITA,DNF,NaN,100 m H,Heats,F,1996

In [0]:
df=df.set_index(['ATHLETE','Year']).sort_index()

In [0]:
df

                                Unnamed: 0  POS     BIB COUNTRY        MARK  \
ATHLETE                   Year
Aaron BROWN               2016        1147  3.0  2192.0  CANCAN       10.24
Abdul GHAFOOR             1996        2257  8.0     NaN  AFGAFG        12.2
Abdul RASHID              2008         378  8.0     NaN  PAKPAK       14.52
Abdul Wahab ZAHIRI        2016        1068  7.0  2000.0  AFGAFG       11.56
Abdullah AL-SOOLI         2008          44  5.0     NaN  OMAOMA       10.53
Abdullah Abkar MOHAMMED   2016        1106  5.0  2717.0  KSAKSA       10.26
Abiodun OYEPITAN          2004        1316  2.0     NaN  GBRGBR     11.23 Q
                          2004        1324  3.0     NaN  GBRGBR     11.28 Q
                          2004        1358  5.0     NaN  GBRGBR       11.18
                          2012         509  5.0  1869.0  GBRGBR     11.22 q
                          2012         551  7.0  1869.0  GBRGBR       11.36
Abraham KEPSIN            2000        1772  8.0     NaN  VANVAN       11.12
Adam GEMILI               2012         639  2.0  1809.0  GBRGBR     10.11 Q
                          2012         679  2.0  1809.0  GBRGBR       10.06
Adrian DURANT             2004        1417  6.0     NaN  ISVISV       10.52
Adrian GRIFFITH           2016        1091  8.0  2067.0  BAHBAH       10.53
Adrian WOODLEY            2000        2037  4.0     NaN  CANCAN     13.71 Q
                          2000        2064  6.0     NaN  CANCAN       14.04
Adrien DEGHELT            2012         778  3.0  1136.0  BELBEL     13.52 Q
                          2012         832  4.0  1136.0  BELBEL       13.42
Afa ISMAIL                2012         460  5.0  2494.0  MDVMDV       12.52
Affoué Amandine ALLOU     2004        1278  4.0     NaN  CIVCIV       11.46
                          2008         174  5.0     NaN  CIVCIV       11.75
Agné EGGERTH              2000        1894  6.0     NaN  LTULTU       11.87
                          2004        1302  4.0     NaN  LTULTU       11.44
Ahmad HAZER               2012         810  9.0  2421.0  LBNLBN       14.82
                          2016        1208  7.0  2731.0  LIBLIB        15.5
Ahmed DOUHOU              1996        2317  5.0     NaN  CIVCIV       10.53
Aisea TOHI                2008          14  7.0     NaN  TGATGA       11.17
Aissata TOURÉ             2012         462  7.0  2021.0  GUIGUI       13.25
...                                    ...  ...     ...     ...         ...
Yuniel HERNÁNDEZ          2004        1683  NaN     NaN  CUBCUB         DNS
Yuriy ARISTOV             1996        2364  8.0     NaN  UZBUZB       15.04
Yvette LEWIS              2016         933  8.0  1081.0  PANPAN       13.35
Yvonne KANAZAWA           1996        2425  5.0     NaN  JPNJPN        13.3
                          2000        2110  5.0     NaN  JPNJPN     13.13 q
                          2000        2150  6.0     NaN  JPNJPN     13.11 q
                          2000        2176  8.0     NaN  JPNJPN       13.16
Zaidatul Husniah ZULKIFLI 2016         960  3.0   999.0  MASMAS     12.12 q
                          2016        1029  8.0   999.0  MASMAS       12.62
Zhanna BLOCK              1996        2192  1.0     NaN  UKRUKR        11.2
                          2000        1873  1.0     NaN  UKRUKR     11.27 Q
                          2000        1956  1.0     NaN  UKRUKR     11.08 Q
                          2000        1974  3.0     NaN  UKRUKR     11.32 Q
                          2000        1991  4.0     NaN  UKRUKR        11.2
                          2004        1306  NaN     NaN  UKRUKR          DQ
                          2004        1337  NaN     NaN  UKRUKR          DQ
                          2004        1369  NaN     NaN  UKRUKR          DQ
Zhenye XIE                2016        1102  1.0  2234.0  CHNCHN     10.08 Q
                          2016        1160  7.0  2234.0  CHNCHN       10.11
Zhivko VIDENOV            2000        2018  NaN     NaN  BULBUL         DNF
Zlatka GEORGIEVA          1996        2188  4.0     NaN  BULBUL       11.74
Ággelos PAVLAKÁKIS        2000        1745  NaN     NaN  GREGRE         DNS
Ángel David RODRÍGUEZ     2008          35  4.0     NaN  ESPESP     10.34 q
                          2008         111  8.0     NaN  ESPESP       10.35
                          2012         609  4.0  1636.0  ESPESP       10.34
Ángela TENORIO            2016         984  3.0   613.0  ECUECU     11.35 q
                          2016        1034  5.0   613.0  ECUECU       11.14
Éder Antonio SOUZA        2016        1213  4.0  2154.0  BRABRA     13.61 Q
                          2016        1250  NaN  2154.0  BRABRA  DQ R 168.7
Édson RIBEIRO             1996        2272  5.0     NaN  BRABRA       10.39

                                RxnTime     Race        Round Gender
ATHLETE                   Year
Aaron BROWN               2016    0.135    100 m        Heats      M
Abdul GHAFOOR             1996      NaN    100 m        Heats      M
Abdul RASHID              2008    0.172  110 m H        Heats      M
Abdul Wahab ZAHIRI        2016    0.170    100 m  Preliminary      M
Abdullah AL-SOOLI         2008    0.153    100 m        Heats      M
Abdullah Abkar MOHAMMED   2016    0.154    100 m        Heats      M
Abiodun OYEPITAN          2004    0.181    100 m        Heats      F
                          2004    0.198    100 m      Quarter      F
                          2004    0.140    100 m         Semi      F
                          2012    0.153    100 m        Heats      F
                          2012    0.151    100 m         Semi      F
Abraham KEPSIN            2000    0.172    100 m        Heats      M
Adam GEMILI               2012    0.156    100 m        Heats      M
                          2012    0.158    100 m         Semi      M
Adrian DURANT             2004    0.223    100 m        Heats      M
Adrian GRIFFITH           2016    0.143    100 m        Heats      M
Adrian WOODLEY            2000    0.175  110 m H        Heats      M
                          2000    0.178  110 m H      Quarter      M
Adrien DEGHELT            2012    0.158  110 m H        Heats      M
                          2012    0.142  110 m H         Semi      M
Afa ISMAIL                2012    0.223    100 m  Preliminary      F
Affoué Amandine ALLOU     2004    0.182    100 m        Heats      F
                          2008    0.204    100 m        Heats      F
Agné EGGERTH              2000    0.277    100 m        Heats      F
                          2004    0.177    100 m        Heats      F
Ahmad HAZER               2012    0.195  110 m H        Heats      M
                          2016    0.144  110 m H        Heats      M
Ahmed DOUHOU              1996      NaN    100 m        Heats      M
Aisea TOHI                2008    0.159    100 m        Heats      M
Aissata TOURÉ             2012    0.198    100 m  Preliminary      F
...                                 ...      ...          ...    ...
Yuniel HERNÁNDEZ          2004      NaN  110 m H         Semi      M
Yuriy ARISTOV             1996      NaN  110 m H        Heats      M
Yvette LEWIS              2016    0.150  100 m H        Heats      F
Yvonne KANAZAWA           1996      NaN  100 m H        Heats      F
                          2000    0.192  100 m H        Heats      F
                          2000    0.184  100 m H      Quarter      F
                          2000      NaN  100 m H         Semi      F
Zaidatul Husniah ZULKIFLI 2016    0.151    100 m  Preliminary      F
                          2016    0.149    100 m        Heats      F
Zhanna BLOCK              1996      NaN    100 m        Heats      F
                          2000    0.215    100 m        Heats      F
                          2000    0.191    100 m      Quarter      F
                          2000    0.227    100 m         Semi      F
                          2000    0.223    100 m        Final      F
                          2004    0.186    100 m        Heats      F
                          2004    0.203    100 m      Quarter      F
                          2004    0.158    100 m         Semi      F
Zhenye XIE                2016    0.143    100 m        Heats      M
                          2016    0.134    100 m         Semi      M
Zhivko VIDENOV            2000    0.122  110 m H        Heats      M
Zlatka GEORGIEVA          1996      NaN    100 m        Heats      F
Ággelos PAVLAKÁKIS        2000      NaN    100 m        Heats      M
Ángel David RODRÍGUEZ     2008    0.145    100 m        Heats      M
                          2008    0.154    100 m      Quarter      M
                          2012    0.168    100 m        Heats      M
Ángela TENORIO            2016    0.150    100 m        Heats      F
                          2016    0.145    100 m         Semi      F
Éder Antonio SOUZA        2016    0.134  110 m H        Heats      M
                          2016    0.137  110 m H         Semi      M
Édson RIBEIRO             1996      NaN    100 m        Heats      M

[2457 rows x 9 columns]

12) But now we have an intuitive index for the data frame.  Instead of accessing something like `df.loc[7]` we can access by name and year (using the same `.loc` attribute).  First just try accessing Usain Bolt's data by name (note that his last name is all capital letters in this dataset).  Note that it will contain results from several races across several years.

Now that `df` has been changed, some of the commands in the earlier questions won't work the same.  So you won't be able to access e.g. `df.loc[7]` anymore, because there is no longer a row named 7!  This is why you should always execute notebooks from top to bottom.  Each notebook cell can change the data in a way that a cell above it doesn't know about.

In [0]:
# Fill in your answer to 12 here
df.loc['Usain BOLT']

      Unnamed: 0  POS     BIB COUNTRY     MARK  RxnTime   Race    Round Gender
Year
2008           0  1.0     NaN  JAMJAM      9.5    0.186  100 m    Heats      M
2008         104  1.0     NaN  JAMJAM   9.92 Q    0.165  100 m  Quarter      M
2008         120  1.0     NaN  JAMJAM   9.85 Q    0.161  100 m     Semi      M
2008         136  1.0     NaN  JAMJAM     9.69    0.165  100 m    Final      M
2012         630  1.0  2170.0  JAMJAM  10.09 Q    0.178  100 m    Heats      M
2012         670  1.0  2170.0  JAMJAM   9.87 Q    0.180  100 m     Semi      M
2012         686  1.0  2170.0  JAMJAM     9.63    0.165  100 m    Final      M
2016        1136  1.0  2612.0  JAMJAM  10.07 Q    0.156  100 m    Heats      M
2016        1162  1.0  2612.0  JAMJAM   9.86 Q    0.143  100 m     Semi      M
2016        1178  1.0  2612.0  JAMJAM     9.81    0.155  100 m    Final      M

13) You can further restrict the data to a single year by using the `.loc` attribute again ("chaining" operations together), and now including a specific year.  Access Usain Bolt's data for 2008.  Hint: it will look just like the answer above, but with an extra `.loc` appended on.

In [0]:
# Fill in your answer to 13 here
df.loc['Usain BOLT'].loc[2008]

      Unnamed: 0  POS  BIB COUNTRY    MARK  RxnTime   Race    Round Gender
Year
2008           0  1.0  NaN  JAMJAM     9.5    0.186  100 m    Heats      M
2008         104  1.0  NaN  JAMJAM  9.92 Q    0.165  100 m  Quarter      M
2008         120  1.0  NaN  JAMJAM  9.85 Q    0.161  100 m     Semi      M
2008         136  1.0  NaN  JAMJAM    9.69    0.165  100 m    Final      M

14) How fast does Usain Bolt react to the starting gun?  Find his minimum Olympic sprint reaction time by acessing his data using `.loc`, accessing reaction time by column name, and then computing the minimum.  Hint: the *maximum* is obtained with the `.max()` method.

In [0]:
df.index

MultiIndex(levels=[['Aaron BROWN', 'Abdul GHAFOOR', 'Abdul RASHID', 'Abdul Wahab ZAHIRI', 'Abdullah AL-SOOLI', 'Abdullah Abkar MOHAMMED', 'Abiodun OYEPITAN', 'Abraham KEPSIN', 'Adam GEMILI', 'Adrian DURANT', 'Adrian GRIFFITH', 'Adrian WOODLEY', 'Adrien DEGHELT', 'Afa ISMAIL', 'Affoué Amandine ALLOU', 'Agné EGGERTH', 'Ahmad HAZER', 'Ahmed DOUHOU', 'Aisea TOHI', 'Aissata TOURÉ', 'Akani SIMBINE', 'Akeem HAYNES', 'Akonga NSIMBO', 'Alaa JASSIM', 'Alberto MÉNDEZ', 'Aleen BAILEY', 'Aleesha BARBER', 'Aleksandra ANTONOVA', 'Aleksandra VOJNESKA', 'Aleksey DREMIN', 'Alexander JOHN', 'Alexander KOSENKOW', 'Alfayaya EMBALO', 'Ali SHAREEF', 'Alina TALAY', 'Aliuska LÓPEZ', 'Allan SCOTT', 'Allen JOHNSON', 'Allison PETER', 'Allyson FELIX', 'Alpha KAMARA', 'Alyssa CONLEY', 'Aléxandros TERZIÁN', 'Aléxandros YENOVÉLIS', 'Amarildo ALMEIDA', 'Ameerah BELLO', 'Aminata CAMARA', 'Aminata DIOUF', 'Aminata KAMISSOKO', 'Amr Ibrahim Mostafa SEOUD', 'Anais OYEMBO', 'Anastasiya SOPRUNOVA', 'Anastassiya PILIPENKO', 'Anatoliy DOVHAL', 'Anay TEJEDA', 'Andre DE GRASSE', 'Andrea COLOMBO', 'Andrea GIACONI', 'Andrea IVANCEVIC', 'Andrea PHILIPP', 'Andreea OGRAZEANU', 'Andrew FISHER', 'Andrew HINDS', 'Andrew POZZI', 'Andrew RILEY', 'Andrew TULLOCH', 'Andrew TURNER', 'Andrew TYNES', 'Andrey EPISHIN', 'Andrey FEDORIV', 'Andrey KISLYKH', 'André DA SILVA', 'Angela ATEDE', 'Angela THORP', 'Angela WHYTE', 'Ani KHACHIKYAN', 'Anier GARCÍA', 'Anita PISTONE', 'Anita TRUMPE', 'Anne ZAGRE', 'Anninos MARCOULLIDES', 'Anselmo DA SILVA', 'Anson HENRY', 'Antoine ADAMS', 'Antoine BOUSSOMBO', 'Antonio ALKANA', 'Antti HAAPAKOSKI', 'Antwon HICKS', 'Anvar KUCHMURADOV', 'Anyika ONUORA', 'Anzhela KRAVCHENKO', 'Aries MERRITT', 'Arif AKHUNDOV', 'Arlindo LEÓCADIO PINHEIRO', 'Arnaldo SILVA', 'Artur Bruno ROJAS', 'Artur NOGA', 'Asafa POWELL', 'Asenate MANOA', 'Asha PHILIP', 'Aska CAMBRIDGE', 'Ato BOLDON', 'Augustine NKETIA', 'Aurelia TRYWIANSKA-KOLLASCH', 'Ayako KIMURA', 'Ayanna HUTCHINSON', 'Aziz OUHADI', 'Aziz ZAKARI', 'Azneem AHMED', 'Balázs BAJI', 'Balázs KOVÁCS', 'Bamab NAPO', 'Barakat Mubarak AL-HARTHI', 'Barbara PIERRE', 'Barnabé JOLICOEUR', 'Basma AL-ESHOSH', 'Beate SCHROTT', 'Beauty NAZMUNNAHAR', 'Ben Youssef MEITÉ', 'Benjamin SIRIMOU', 'Berenger Aymard BOSSE', 'Bettina MÜLLER-WEISSINA', 'Beverly MCDONALD', 'Bibiana Martina OLAMA', 'Bich Huong VU', 'Bimal TARAFDAR', 'Bingtian SU', 'Birgit WOLF', 'Blessing OKAGBARE', 'Bonifacio EDÚ', 'Bonko CAMARA', 'Boureima KIMBA', 'Brenessa THOMPSON', 'Brianna ROLLINS', 'Brigita BUKOVEC', 'Brigitte FOSTER-HYLTON', 'Brigitte MERLANO', 'Brijesh LAWRENCE', 'Bruny SURIN', 'Bui LUONG', 'Buthaina AL-YAQOOBI', 'Caimin DOUGLAS', 'Calvin KANG LI LOONG', 'Caridad JEREZ', 'Carina HORN', 'Carla TUZZI', 'Carlos ABAUNZA', 'Carlos GATS', 'Carlos SALA', 'Carmelita JETER', 'Carol MOKOLA', 'Carolin DIETRICH', 'Cecilia BOUELE', 'Cejhae GREENE', 'Chaleunsouk AO UDOMPHANH', 'Chan Than OUK', 'Chandra Kala THAPA', 'Chandra STURRUP', 'Charlene ATTARD', 'Charles ALLEN', 'Charlotte WINGFIELD', 'Chauzje CHOOSHA', 'Cherico DETENAMO', 'Cheryl DICKEY', 'Chiang Wai HUNG', 'Chijindu UJAH', 'Chintake DE SOYSA', 'Chioma AJUNWA', 'Chisato FUKUSHIMA', 'Chris DONALDSON', 'Chris Meke WALASI', 'Chris PINNOCK', 'Christania WILLIAMS', 'Christian NSIAH', 'Christie VAN WYK', 'Christina VUKICEVIC', 'Christine ARRON', 'Christophe LEMAITRE', 'Christopher LIMA DA COSTA', 'Christopher Silas ADOLF', 'Christopher WILLIAMS', 'Chryste GAINES', 'Chun Ho LAI', 'Churandy MARTINA', 'Cindy BILLAUD', 'Cindy OFILI', 'Cindy ROLEDER', 'Claes ALBIHN', 'Claude EDORH', 'Cleide AMARAL', 'Cláudio Roberto SOUZA', 'Clélia REUSE-RARD', 'Colin JACKSON', 'Cora ALICTO', 'Courtney WILLIAMS', 'Craig PICKERING', 'Cristina LLOVERA', 'Crystal EMMANUEL', 'Curt YOUNG', 'Curtis JOHNSON', 'Cydonie MOTHERSILLE', 'Cécile CINÉLU', 'Céline LAPORTE', 'D'Andre HILL', 'Dafne SCHIPPERS', 'Damian CZYKIER', 'Damien GREAVES', 'Damjan ZLATNAR', 'Damu CHERRY', 'Danah AL NASRALLAH', 'Danah HUSSEIN', 'Daniel BAILEY', 'Daniel GRUESO', 'Danny D'SOUZA', 'Daria KORCZYNSKA', 'Dariusz KUC', 'Darrel BROWN', 'Darrell WESH', 'Darren BRAITHWAITE', 'Darren CAMPBELL', 'Darren GILFORD', 'Darvis PATTON', 'Daryll NEITA', 'David ILARIANI', 'David OLIVER', 'David PATROS', 'David PAYNE', 'Davidson EZINWA', 'Dawn HARPER NELSON', 'Dayron ROBLES', 'DeVon BEAN', 'Debbie EDWARDS', 'Debbie FERGUSON-MCKENZIE', 'Dedeh ERAWATI', 'Dejan VOJNOVIC', 'Deji ALIU', 'Delloreen ENNIS-LONDON', 'Delphine ATANGANA', 'Denika KASSIM', 'Dennis MITCHELL', 'Derrick ATKINS', 'Derval O'ROURKE', 'Desiree HENRY', 'Desislav GUNEV', 'Deuce CARTER', 'Devi Maya PANERU', 'Devilert Arsene KIMBEMBE', 'Devon ALLEN', 'Diane ALLAHGREEN', 'Diane BORG', 'Diego FERREIRA', 'Dimitri BASCOU', 'Dionne ROSE-HENLEY', 'Dipna LIM PRASAD', 'Djikoloum MOBELE', 'Dmytro HLUSHCHENKO', 'Donald ONCHIRI', 'Dongpeng SHI', 'Donovan BAILEY', 'Duane ROSS', 'Dudley DORIVAL', 'Dutee CHAND', 'Dwain CHAMBERS', 'Dwight THOMAS', 'Dániel KISS', 'Eddie LOVETT', 'Eddy DE LEPINE', 'Edgardo A. SERPAS', 'Edit VÁRI', 'Edy JAKARIYA', 'Ekaterina GALITSKAIA', 'Ekaterina POPLAVSKAYA', 'Ekateríni KÓFFA', 'Ekateríni THÁNOU', 'Ekundayo WILLIAMS', 'Elaine THOMPSON', 'Elama FA'ATONU', 'Eldece CLARKE-LEWIS', 'Elena BOBROVSKAYA', 'Eliecith PALACIOS', 'Eline BERINGS', 'Elis LAPENMAL', 'Elisabeta ANGHEL', 'Elisávet PESIRÍDOU', 'Elmar LICHTENEGGER', 'Elvira DZHABAROVA', 'Emanuele ABATE', 'Emerson PERIN', 'Emiliano PIZZOLI', 'Emilio VALLE', 'Emma WADE', 'Emmanuel MATADI', 'Emmanuel ROMARY', 'Emmanuel TUFFOUR', 'Endurance OJOKOLO', 'Ene Franca IDOKO', 'English GARDNER', 'Enrique LLANOS', 'Eric AGUEH', 'Eric KAISER', 'Eric NKANSAH', 'Eric Pacome N'DRI', 'Erik BALNUWEIT', 'Erik BATTE', 'Erik WIJMEERSCH', 'Erwin Heru SUSANTO', 'Esi BENYARKU', 'Etimoni TIMUANI', 'Eugene SWIFT', 'Evangeleen IKELAP', 'Evelyn RIVERA', 'Evgeniy BORISOV', 'Evgeniya POLYAKOVA', 'Ewa SWOBODA', 'Ezinne OKPARAEBO', 'Ezio MADONIA', 'Fabiana MORÃES', 'Fabio CERUTTI', 'Fabrice COIFFIC', 'Fadwa AL BOUZA', 'Falk BALZER', 'Fana ASHBY', 'Fartun ABUKAR OMAR', 'Fathia ALI BOURALEH', 'Fatima Sulaiman DAHMAN', 'Fatmata FOFANAH', 'Fatou DIENG', 'Fatou TIYANA', 'Fawaz AL-SHAMMARI', 'Fawaz Ismail JOHAR', 'Felipe VIVANCOS', 'Femi OGUNODE', 'Fernando ARLETE', 'Fernando LUMAIN', 'Feta AHAMADA', 'Filipo MULLER', 'Flings OWUSU-AGYAPONG', 'Florian SCHWARTHOFF', 'Flóra REDOÚMI', 'Foo Ee YEO', 'Foujia HUDA', 'Francesco SCUDERI', 'Franciela KRASUCKI', 'Francis MANIORU', 'Francis OBIKWELU', 'Franck AMÉGNIGAN', 'Frank FREDERICKS', 'Frank MENSAH', 'Franklin NAZARENO', 'Freddy MAYOLA', 'Frutos FEO', 'Gabriel BURNETT', 'Gabriel MVUMVURE', 'Gabriel SIMÓN', 'Gail DEVERS', 'Garfield DARIEN', 'Gennadiy CHERNOVOL', 'George BOROI', 'Gerald PHIRI', 'Geraldine PILLAY', 'Gharid GHROUF', 'Ghyd Kermeliss OLONGHOT', 'Gian Nicola BERARDI', 'Gillian RUSSELL-LOVE', 'Glenroy GILBERT', 'Gloria ASUMNU', 'Glory ALOZIE', 'Gordon Teokotai HEATHER', 'Grace DINKINS', 'Greggmar SWIFT', 'Gregor TRABER', 'Gregory SEDOC', 'Guillermo DONGO', 'Guntis PEDERS', 'Guzel KHUBBIEVA', 'Gwen TORRENCE', 'Gábor DOBOS', 'Gérard KOBÉANÉ', 'Hadhari DJAFFAR', 'Hafsatu KAMARA', 'Haijian CHEN', 'Hajar ALKHALDI', 'Hakim MAZOU', 'Hala GEZAH', 'Halimat ISMAILA', 'Hamed Hadib SADEQ', 'Hanitriniaina RAKOTONDRABE', 'Hanna PLOTITSYNA', 'Hannah COOPER', 'Hansle PARCHMENT', 'Harmon HARMON', 'Harálabos PAPADIÁS', 'Haseri ASLI', 'Hassan SAAID', 'Hassan TAFTIAN', 'Hawanatu BANGURA', 'Heather SAMUEL', 'Heber VIERA', 'Heidi HANNULA', 'Henricho BRUINTJIES', 'Henry ANDRADE', 'Henry VIZCAÍNO', 'Hermenegildo LEITE', 'Hermin JOSEPH', 'Herwig RÖTTL', 'Hinikissia Albertine NDIKERT', 'Hiroyasu TSUCHIE', 'Holder DA SILVA', 'Hristóforos HOÍDIS', 'Hsin-Ping HUANG', 'Hua Wilfried KOFFI', 'Huei-Chen WANG', 'Hyelim JUNG', 'Héctor COTTO', 'Ian MACKIE', 'Ibrahim MEITÉ', 'Idrissa ADAM', 'Idrissa SANOU', 'Igor KOVÁC', 'Igor PEREMOTA', 'Igors KAZANOVS', 'Iman Essa JASIM', 'Ime AKPAN', 'Inna EFTIMOVA', 'Irene TRUICE JOSEPH', 'Irina KHABAROVA', 'Irina LENSKIY', 'Irina PRIVALOVA', 'Irina SHEVCHENKO', 'Iryna PUKHA', 'Isaac SILAFAU', 'Isabelle PEDERSEN', 'Isidro MONTOYA', 'Ismail KAMARA', 'Ismenia FREDERICO', 'Issa-Aimé NTHÉPÉ', 'Ivana ROHMAN', 'Ivanique KEMP', 'Ivet LALOVA', 'Ivet LALOVA-COLLIO', 'J'Maal ALEXANDER', 'Jack HOWARD', 'Jackie AGYEPONG', 'Jackson QUIÑÓNEZ', 'Jade BAILEY', 'Jahvid BEST', 'Jak Ali HARVEY', 'Jamal Abd. AL-SAFFAR', 'James DASAOLU', 'James ELLINGTON', 'Jamial ROLLE', 'Janice ALATOA', 'Janis ROUBABA', 'Jarbas MASCARENHAS', 'Jared LEWIS', 'Jasmine CAMACHO-QUINN', 'Jason GARDENER', 'Jason RICHARDSON', 'Jason ROGERS', 'Javier VERME', 'Jaysuma SAIDY NDURE', 'Jean-Aime RANDRIANALIJAONA', 'Jean-Marc GRAVA', 'Jean-Olivier ZIRIGNON', 'Jeanette KWAKYE', 'Jeff PORTER', 'Jeffrey JACKSON', 'Jeffrey JULMIS', 'Jeimy BERNÁRDEZ', 'Jennifer MADU', 'Jenny KALLUR', 'Jenny KENI', 'Jeremy BASCOM', 'Jerneja PERC', 'Jerome CREWS', 'Jesse TAMANGROW', 'Jessica AGUILERA', 'Jessica ENNIS-HILL', 'Jessica ZELINKA', 'Jesús FONT', 'Jhoanis PORTILLA', 'Jiankui YAN', 'Jidou EL MOCTAR', 'Jimmy VICAUT', 'Jin Wei Timothee YAP', 'Jing WANG', 'Joan Uduak EKAH', 'Joanna HAYES', 'Joanna HOAREAU', 'Joanne DURANT', 'Joel MASCOLL', 'Johan LISABETH', 'Johanna MANNINEN', 'John HOWARD', 'John MURAY', 'John RUUKA', 'Johnathan CABRAL', 'Joice MADUAKA', 'Jon DRUMMOND', 'Jonathan NSENGA', 'Jone DELAI', 'Jordan MAGEO', 'Jorge CASTELLÓN', 'Joseph Andy LUI', 'Joseph BATANGDON', 'Joseph-Berlioz RANDRIAMIHAJA', 'Josephine ONYIA', 'Joshua ROSS', 'José Carlos MOREIRA', 'José David RIESCO', 'Jovesa NAIVALU', 'João Carlos ALMEIDA', 'João Vitor DE OLIVEIRA', 'Juan SAINFLEUR', 'Judex LEFOU', 'Julian REUS', 'Juliana NZANG OBIENG', 'Juliane SPRENGER-AFFLERBACH', 'Julie BAUMANN', 'Juliet CUTHBERT', 'Jung-joon LEE', 'Jurgen THEMEN', 'Jurica GRABUIC', 'Justin GATLIN', 'Justyn WARNER', 'Jutamass TAWONCHAROEN', 'Kadiatou CAMARA', 'Kai HU', 'Kaina MARTINEZ', 'Kaingaue DAVID', 'Kaitinano MWEMWEATA', 'Kakianako NARIKI', 'Kame ALI', 'Kamia YOUSUFI', 'Kapiriel KITSON', 'Kareem STREETE-THOMPSON', 'Kariman ABULJADAYEL', 'Karin MAYR-KRIFKA', 'Karitaake TEWAAKI', 'Karolina KOLECZEK', 'Katerina CECHOVÁ', 'Katura MARAE', 'Katy SEALY', 'Kellie WELLS', 'Kelly-Ann BAPTISTE', 'Kelsey NAKANELUA', 'Kemar HYMAN', 'Kemarley BROWN', 'Kerri-Ann MITCHELL', 'Kerron STEWART', 'Keston BLEDMAN', 'Keturah ANDERSON', 'Khaled OTHMAN', 'Khalil AL-HANAHNEH', 'Khamica BINGHAM', 'Khrystyna STUY', 'Kierre BECKLES', 'Kilakone SIPHONEXAY', 'Kim COLLINS', 'Kim GEVAERT', 'Kin Yee WAN', 'Kirk CUMMINS', 'Kirsten BOLM', 'Koji ITO', 'Konstadínos DOUVALÍDIS', 'Konstantin SHABANOV', 'Kostyantyn RURAK', 'Kristi CASTLIN', 'Kristin PATZWAHL', 'Krzysztof MEHLICH', 'Kukyoung KIM', 'Kyle VANDER KUYP', 'LaTasha COLANDER', 'LaToya GREAVES', 'LaVerne JONES-FERRETTE', 'Lacena GOLDING-CLARKE', 'Ladji DOUCOURÉ', 'Laenly PHOUTTHAVONG', 'Lamin TUCKER', 'Larisa KRUGLOVA', 'Laura TURNER', 'Laure KUETEY', 'Lauren HEWITT', 'Lauryn WILLIAMS', 'Lavonne IDLETTE', 'Lawrence CLARKE', 'Lecabela QUARESMA', 'Lehann FOURIE', 'Lena SOLLI-REIMANN', 'Leon GORDON', 'Leonard MYLES-MILLS', 'Lerissa HENRY', 'Lerma GABITO', 'Lesley TASHLIN', 'Levente CSILLAG', 'Liaqat ALI', 'Lidiane LOPES', 'Lidiya YURKOVA', 'Liliana ALLEN', 'Liliana NETO', 'Lina BEJJANI', 'Lina FLÓREZ', 'Lina GRINCIKAITÉ-SAMUOLE', 'Linda FERGA-KHODADIN', 'Lindel FRATER', 'Linford CHRISTIE', 'LoLo JONES', 'Lorène Dorcas BAZOLO', 'Louise AYÉTOTCHÉ', 'Lucas JAKUBCZYK', 'Lucas NELSON', 'Lucie KROBÁKOVÁ', 'Lucimar Aparecida DE MOURA', 'Lucrécia JARDIM', 'Ludmila ENGQUIST', 'Lukasz CHYLA', 'Luke BEZZINA', 'Luká MILO', 'Luz Marina GEERMAN', 'Luís CUNHA', 'Luís SÁ', 'Lynda TOLBERT-GOODE', 'Lyubov PEREPELOVA', 'Lyudmila DMITRIADI', 'M'Mah TOURE', 'Mae KOIME', 'Magali FRANKA', 'Mahesh PERERA', 'Makoura KEITA', 'Maksim LYNSHA', 'Mamane Sani ALI', 'Manuel BORREGA', 'Manuela BOSCO', 'Marc BLUME', 'Marc BURNS', 'Marcel VAN DER WESTEN', 'Marcia RICHARDSON', 'Marcin KUSZEWSKI', 'Marcin NOWAK', 'Marek NIIT', 'Mari Paz MOSANGA MOTANGA', 'Maria BELIMPASAKI', 'Maria IKELAP', 'Maria-Joelle CONJUNGO', 'Mariam Mohamed Hadi AL HILLI', 'Mariana CRESS', 'Marie-Josee TA LOU', 'Marika POPOWICZ-DRAPALA', 'Marina TOMIC', 'Marina TRANDENKOVA', 'Marine GHAZARYAN', 'Mario BONELLO', 'Marion JONES', 'Mariya KOROTEYEVA', 'Mark CREAR', 'Mark LEWIS-FRANCIS', 'Mark MCKOY', 'Mark SHERWIN', 'Marta JESCHKE', 'Martha ADUSEI', 'Marthe KOALA', 'Martial MBANDJOCK', 'Martin LACHKOVICS', 'Martina PRETELLI', 'Marvin BRACY', 'Mary ONYALI-OMAGBEMI', 'Mary TOMBIRI', 'Marzia CARAVELLI', 'María José MARDOMINGO', 'Masashi ERIGUCHI', 'Masato NAITO', 'Masbah AHMMED', 'Massoud AZIZI', 'Mateus Facho INOCÊNCIO', 'Mathew QUINN', 'Matic OSOVNIKAR', 'Matthew SHIRVINGTON', 'Matthias BÜHLER', 'Maurice GREENE', 'Maurice WIGNALL', 'Maya SHEMCHYSHENA', 'Mayra MAYBERRY', 'Maysa REJEPOVA', 'Mazoon AL-ALAWI', 'Maíla MACHADO', 'Md Fakhri ISMAIL', 'Megan SIMMONDS', 'Melanie PASCHKE', 'Melinda GAINSFORD-TAYLOR', 'Melisa MURILLO', 'Melissa BREEN', 'Melissa MORRISON-HOWARD', 'Mercy NKU', 'Merlene OTTEY', 'Mhadjou YOUSSOUF', 'Michael FRATER', 'Michael GREEN', 'Michael MARSH', 'Michaela KARGBO', 'Michelle BAPTISTE', 'Michelle FREEMAN', 'Michelle JENNEKE', 'Michelle-Lee AHYE', 'Micol CATTANEO', 'Miguel DE LOS SANTOS', 'Miguel LÓPEZ', 'Miguel SOTO', 'Mihter WENDOLIN', 'Mike FENNER', 'Mikel THOMAS', 'Milan RISTIC', 'Milan TRAJKOVIC', 'Milena MILAEVIC', 'Mireille DONDERS', 'Miriam CUPÁKOVÁ', 'Mirtha BROCK', 'Mitchell PETERS', 'Mohamed ABU ABDULLAH', 'Mohamed BACAR', 'Mohamed Issa AL-THAWADI', 'Mohamed Lamine DANSOKO', 'Mohammad SHAMSUDDIN', 'Mohammed ABUKHOUSA', 'Mohan KHAN', 'Monica TWUM', 'Monique ÉWANJÉ-ÉPÉE TOURRET', 'Montell DOUGLAS', 'Montserrat PUJOL', 'Moses KAMUT', 'Moses OYIKI', 'Mosito LEHATA', 'Moumi SEBERGUE', 'Moussa DEMBELE', 'Mubarak Ata MUBARAK', 'Mujinga KAMBUNDJI', 'Mulern JEAN', 'Muna LEE', 'Murielle AHOURÉ', 'Myriam Léonie MANI', 'Myriam SOUMARÉ', 'Márcio Simão DE SOUZA', 'Nabie Foday FOFANA', 'Nadezhda BODROVA', 'Nadine FAUSTIN-PARKER', 'Nadine HENTSCHKE', 'Nadine HILDEBRAND', 'Nadine VISSER', 'Nafissa SOULEYMANE', 'Naide GOMES', 'Naoki TSUKAHARA', 'Narcisa LANDAZURI', 'Natalia POHREBNIAK', 'Natalia RUSAKOVA', 'Natalie MARTINDALE', 'Natalya GRIGORYEVA', 'Natalya IGNATOVA', 'Natalya IVONINSKAYA', 'Natalya MURINOVICH', 'Natalya POMOSHCHNIKOVA-VORONOVA', 'Natalya SHEKHODANOVA', 'Natalya VOROBYEVA', 'Natasha MAYERS', 'Needy GUIMS', 'Neil RYAN', 'Nenad LONCAR', 'Nester GENIWALA'A', 'Nevin YANIT', 'Ngerak FLORENCIO', 'Nia ALI', 'Nickel ASHMEADE', 'Nickiesha WILSON', 'Nicolas MACROZONARIS', 'Nicole RAMALALANIRINA', 'Niconnor ALEXANDER', 'Nigina SHARIPOVA', 'Nikkita HOLDER', 'Nilson ANDRÈ', 'Nimet KARAKUS', 'Nirinaharifidy RAMILIJAONA', 'Nobuharu ASAHARA', 'Noemi ZBÄREN', 'Nooa TAKOOA', 'Noor Hussain AL-MALKI', 'Nooralotta NEZIRI', 'Nouredine OULD MENIRA', 'Nur Herman MAJID', 'Obadele THOMPSON', 'Obinna METU', 'Odair Pericles DA COSTA', 'Odiah SIDIBÉ', 'Odile AHOUANWANOU', 'Ogho-Oghene EGWERO', 'Okilani TINILAU', 'Oksana SHKURAT', 'Olapade ADENIKEN', 'Oleg NORMATOV', 'Olena KRASOVSKA', 'Olena YANOVSKA', 'Olesya POVKH', 'Olga KHARITONOVA', 'Olga SAFRONOVA', 'Olga SHISHIGINA', 'Oltjon LULI', 'Oludamola OSAYOMI', 'Olusoji A. FASUBA', 'Olutoyin AUGUSTUS', 'Oluwatobiloba AMUSAN', 'Omar MCLEOD', 'Orlando ORTEGA', 'Oscar MENESES', 'Ousmane DIARRA', 'Pa Modou GAI', 'Pamela DUTKIEWICZ', 'Paolo DELLA SANTA', 'Paraskevi PATOULIDOU', 'Pascal MARTINOT-LAGARDE', 'Pascal THÉOPHILE', 'Pastora CHAVEZ', 'Patricia GIRARD', 'Patricia TAEA', 'Patrick JARRETT', 'Patrick JOHNSON', 'Patrick MOCCI RAOUMBÉ', 'Patrick STEVENS', 'Patrick TUARA', 'Patrik STRENIUS', 'Paul BRIZZEL', 'Paul DI BELLA', 'Paul HENDERSON', 'Paul SEHZUE', 'Paul TUCKER', 'Paul WILLIAMS', 'Pauline KWALEA', 'Paulo VILLAR', 'Pedro CHIAMULERA', 'Pedrya SEYMOUR', 'Peimeng ZHANG', 'Peoria KOSHIBA', 'Perdita FELICIEN', 'Peter COGHLAN', 'Peter EMELIEZE', 'Peter KARLSSON', 'Peter PULU', 'Petko YANKOV', 'Petr SVOBODA', 'Petya PENDAREVA', 'Philam GARCIA', 'Philaylack SACKPRASEUTH', 'Phobay KUTU-AKOI', 'Phumlile NDZINISA', 'Phylicia GEORGE', 'Pia TAJNIKAR', 'Pierre BROWNE', 'Pierre DE WINDT', 'Piotr BALCERZAK', 'Pramila RIJAL', 'Prenam PESSE', 'Priscilla LOPES-SCHLIEP', 'Prodromos KATSANTONIS', 'Qiqi YUAN', 'Rabangaki NAWAI', 'Rachael ROGERS', 'Rachid CHOUHAL', 'Rahamatou DRAME', 'Rakia AL-GASSRA', 'Ralf LEBERER', 'Ramon GITTENS', 'Ramona PAPAIOANNOU', 'Raphael DE OLIVEIRA', 'Raphaël MONACHON', 'Raymond STEWART', 'Rebekka HAASE', 'Redelén DOS SANTOS', 'Regina SHOTARO', 'Reginaldo MICHA NDONG', 'Regine TUGADE', 'Renward WELLS', 'Reza GHASEMI', 'Reïna-Flor OKORI', 'Richard PHILLIPS', 'Richard THOMPSON', 'Richson SIMEON', 'Rima KASHAFUTDINOVA', 'Rima TAHA', 'Riste PANDEV', 'Robert FOSTER', 'Robert KRONBERG', 'Robert LOUA', 'Robert M. DENNIS', 'Robert NEWTON', 'Robin KORVING', 'Robina MUQIMYAR', 'Rod MAPSTONE', 'Rodman TELTULL', 'Rohollah ASGARI', 'Roland NÉMETH', 'Rolando PALACIOS', 'Roman CRESS', 'Ronald BENNETT', 'Ronald FORBES', 'Ronald POGNON', 'Ronald PROMESSE', 'Rondel SORRILLO', 'Ronnie ASH', 'Rosa RAKOTOZAFY', 'Rosangela SANTOS', 'Rosemar Maria NETO', 'Rosvitha OKOU', 'Rubie Joy GABRIEL', 'Rubén BENÍTEZ', 'Ruddy ZANG MILAMA', 'Ruslan ABBASOV', 'Ruslan RUSIDZE', 'Ryan BAILEY', 'Ryan BRATHWAITE', 'Ryota YAMAGATA', 'Rytis SAKALAUSKAS', 'Sadaf SIDDIQUI', 'Salem Mubarak AL-YAMI', 'Sally PEARSON', 'Samuel COCO-VILOIN', 'Samuel FRANCIS', 'Sandjema BATOULI', 'Sandra CITTE', 'Sandra GOMIS', 'Sandra P. BORRERO', 'Sandro VIANA', 'Sanna HERNESNIEMI-KYLLÖNEN', 'Sanusi TURAY', 'Sarah CLAXTON', 'Sarah REILLY', 'Sarah TONDE', 'Saruba COLLEY', 'Sasha SPRINGER', 'Satoru TANIGAWA', 'Sau Ying CHAN', 'Savatheda FYNES', 'Saviour SPITERI', 'Sayon COOPER', 'Sean CAHILL', 'Sean SAFO-ANTWI', 'Sebergue MOUMI', 'Sekou KABA', 'Selim NURUDEEN', 'Semoy HACKETT', 'Seng Song POH', 'Serge BENGONO', 'Sergejs INAKOVS', 'Sergey BYCHKOV', 'Sergey CHEPIGA', 'Sergey SHUBENKOV', 'Sergiy OSOVYCH', 'Serhiy DEMYDYUK', 'Seun ADIGUN', 'Seun OGUNKOYA', 'Seye OGUNLEWE', 'Shamar SANDS', 'Shamha AHMED', 'Shanahan SANITOA', 'Shane BRATHWAITE', 'Shani ANDERSON', 'Sharon COUCH', 'Shaun BOWNES', 'Shavez HART', 'Shawn CRAWFORD', 'Shelly-Ann FRASER-PRYCE', 'Sheniqua FERGUSON', 'Shermaine WILLIAMS', 'Sherone SIMPSON', 'Sherry FLETCHER', 'Sherwin VRIES', 'Shigeyuki KOJIMA', 'Shingo KAWABATA', 'Shingo SUETSUGU', 'Shinoona Salah AL-HABSI', 'Shirin AKTER', 'Shu-Chuan CHEN', 'Shuijiao WU', 'Silke LICHTENHAGEN', 'Silvia PANGUANA', 'Simeon WILLIAMSON', 'Simmone JACOBS', 'Simone COLLIO', 'Sina SCHIELKE', 'Sisila SEAVULA', 'Sisomphone VONGPHAKDY', 'Siueni FILIMONE', 'Siulolo LIKU', 'Solomon BOCKARIE', 'Sonata TAMOAITYTE', 'Sonia PAQUETTE', 'Sonia WILLIAMS', 'Sopheak PHOUK', 'Sortelina DA SILVA', 'Souhalia ALAMOU', 'Souksavanh TONSACKTHEVA', 'Sriyani KULAWANSA-FONSECA', 'Stanislav SAJDOK', 'Stanislavs OLIJARS', 'Stefan BURKART', 'Stefano TILLI', 'Stelios BISBAS', 'Stephanie DOUGLAS', 'Stephen JONES', 'Steve ADEGBITE', 'Steve BROWN', 'Stéphane BUCKLAND', 'Sudirman HADI', 'Sultan SAEED', 'Sultan TUCKER', 'Sun-kuk JIN', 'Sunayna WAHI', 'Sunday EMMANUEL', 'Suryo Agung WIBOWO', 'Susanna KALLUR', 'Susanthika JAYASINGHE', 'Suwaibou SANNEH', 'Sven PIETERS', 'Svetla PISHTIKOVA', 'Svetlana LAUKHOVA', 'Sébastien GATTUSO', 'Taeyong PARK', 'Tahesia HARRIGAN-SCOTT', 'Tahmina KOHISTANI', 'Taina HALASIMA', 'Taiwo ALADEFA-DARDEN', 'Tamara SHANIDZE', 'Tamicka CLARKE', 'Tarmo JALLAI', 'Tatjana PINTO', 'Tatyana DEKTYAREVA', 'Tatyana RESHETNIKOVA', 'Tavevele NOA', 'Tayna LAWRENCE', 'Teinakore TEITI', 'Terrence TRAMMELL', 'Tetyana TKALICH', 'Teymur GASIMOV', 'Tezzhan NAIMOVA', 'Thi Huong VU', 'Thomas J. KEARNS', 'Tianna BARTOLETTA', 'Tiffany PORTER', 'Tilak Ram THARU', 'Tim KROEKER', 'Timi GARSTANG', 'Tit Linda SOU', 'Tobias UNGER', 'Todd MATTHEWS-JOUDA', 'Toea WISIL', 'Toluta'u KOULA', 'Tomasz SCIGACZEWSKI', 'Tommi HARTONEN', 'Tommy KAFRI', 'Tomá DVORÁK', 'Tong LI', 'Tony JARRETT', 'Torbjörn ERIKSSON', 'Tori BOWIE', 'Torri EDWARDS', 'Trayvon BROMELL', 'Trecia ROBERTS', 'Tynia GAITHER', 'Tyrone EDGAR', 'Tyson GAY', 'Uchenna EMEDOLU', 'U

In [0]:
# Fill in your answer to 14 here
df.loc['Usain BOLT','RxnTime'].min()

0.14300000000000002

15) Usain Bolt was the fastest 100m sprinter of all time, but he didn't try his hardest until the finals of each meet (he didn't need to).  Let's extract only his data from the finals.  This takes only one step, but we'll do it in two to make the idea clear.  First, let's generate a series that tells us whether it is True or False that a given race was a final.  Just paste `df['Round'] == 'Final'` in the cell below.  You will see a series containig some `True` values and some `False` values (mostly the latter), reflecting rows containing data from finals vs. other rounds.  Note the ellipsis halfway down, which represents all the data (hundreds of rows) it isn't showing you to save space.

In [0]:
# Fill in your answer to 15 here
df['Round']=='Final'

ATHLETE                    Year
Aaron BROWN                2016    False
Abdul GHAFOOR              1996    False
Abdul RASHID               2008    False
Abdul Wahab ZAHIRI         2016    False
Abdullah AL-SOOLI          2008    False
Abdullah Abkar MOHAMMED    2016    False
Abiodun OYEPITAN           2004    False
                           2004    False
                           2004    False
                           2012    False
                           2012    False
Abraham KEPSIN             2000    False
Adam GEMILI                2012    False
                           2012    False
Adrian DURANT              2004    False
Adrian GRIFFITH            2016    False
Adrian WOODLEY             2000    False
                           2000    False
Adrien DEGHELT             2012    False
                           2012    False
Afa ISMAIL                 2012    False
Affoué Amandine ALLOU      2004    False
                           2008    False
Agné EGGERTH               2000    False
                           2004    False
Ahmad HAZER                2012    False
                           2016    False
Ahmed DOUHOU               1996    False
Aisea TOHI                 2008    False
Aissata TOURÉ              2012    False
                                   ...
Yuniel HERNÁNDEZ           2004    False
Yuriy ARISTOV              1996    False
Yvette LEWIS               2016    False
Yvonne KANAZAWA            1996    False
                           2000    False
                           2000    False
                           2000    False
Zaidatul Husniah ZULKIFLI  2016    False
                           2016    False
Zhanna BLOCK               1996    False
                           2000    False
                           2000    False
                           2000    False
                           2000     True
                           2004    False
                           2004    False
                           2004    False
Zhenye XIE                 2016    False
                           2016    False
Zhivko VIDENOV             2000    False
Zlatka GEORGIEVA           1996    False
Ággelos PAVLAKÁKIS         2000    False
Ángel David RODRÍGUEZ      2008    False
                           2008    False
                           2012    False
Ángela TENORIO             2016    False
                           2016    False
Éder Antonio SOUZA         2016    False
                           2016    False
Édson RIBEIRO              1996    False
Name: Round, Length: 2457, dtype: bool

16) The expression above can be used as a "selector", to select data from the dataframe which matches the desired condition (i.e. only 200 m races).  Place it inside brackets (i.e. inside `df[]`) to access only the 200 m races from the original data.

In [0]:
df[df['Round']=='Final']

                              Unnamed: 0  POS     BIB COUNTRY   MARK  RxnTime  \
ATHLETE                 Year
Akani SIMBINE           2016        1182  5.0  2909.0  RSARSA   9.94    0.128
Aleen BAILEY            2004        1374  5.0     NaN  JAMJAM  11.05    0.208
Aliuska LÓPEZ           2000        2181  5.0     NaN  CUBCUB  12.83    0.179
Allen JOHNSON           2000        2094  4.0     NaN  USAUSA  13.23    0.182
Allyson FELIX           2012         573  5.0  3287.0  USAUSA  10.89    0.176
Andre DE GRASSE         2016        1180  3.0  2196.0  CANCAN   9.91    0.141
Angela WHYTE            2004        1585  6.0     NaN  CANCAN  12.81    0.155
Anier GARCÍA            2000        2091  1.0     NaN  CUBCUB     13    0.172
                        2004        1686  3.0     NaN  CUBCUB   13.2    0.169
Aries MERRITT           2012         854  1.0  3236.0  USAUSA  12.92    0.143
Artur NOGA              2008         452  5.0     NaN  POLPOL  13.36    0.169
Asafa POWELL            2004        1522  5.0     NaN  JAMJAM   9.94    0.166
                        2008         140  5.0     NaN  JAMJAM   9.95    0.134
                        2012         692  7.0  2184.0  JAMJAM  11.99    0.155
Ato BOLDON              2000        1850  2.0     NaN  TTOTTO   9.99    0.136
Aziz ZAKARI             2000        1856  NaN     NaN  GHAGHA    DNF    0.180
                        2004        1525  NaN     NaN  GHAGHA    DNF    0.178
Beate SCHROTT           2012         774  7.0  1093.0  AUTAUT  13.07    0.156
Ben Youssef MEITÉ       2016        1183  6.0  2245.0  CIVCIV   9.96    0.156
Blessing OKAGBARE       2012         576  8.0  2584.0  NGRNGR  11.01    0.165
Brianna ROLLINS         2016         862  1.0  1369.0     USA  12.48    0.158
Brigitte FOSTER-HYLTON  2000        2184  8.0     NaN  JAMJAM  13.49    0.217
                        2008         354  6.0     NaN  JAMJAM  12.66    0.167
Carmelita JETER         2012         570  2.0  3299.0  USAUSA  10.78    0.153
Chandra STURRUP         2000        1992  5.0     NaN  BAHBAH  11.21    0.193
Charles ALLEN           2004        1689  6.0     NaN  CANCAN  13.48    0.139
Christania WILLIAMS     2016        1061  8.0   905.0  JAMJAM   11.8    0.163
Churandy MARTINA        2008         139  4.0     NaN  AHOAHO   9.93    0.169
                        2012         690  5.0  2547.0  NEDNED   9.94    0.139
Cindy OFILI             2016         865  4.0   713.0     GBR  12.63    0.161
...                                  ...  ...     ...     ...    ...      ...
Sally PEARSON           2012         768  1.0  1079.0  AUSAUS  12.35    0.137
Sarah CLAXTON           2008         356  8.0     NaN  GBRGBR  12.94    0.163
Savatheda FYNES         2000        1993  6.0     NaN  BAHBAH  11.22    0.253
Shawn CRAWFORD          2004        1521  4.0     NaN  USAUSA   9.89    0.161
Shelly-Ann FRASER-PRYCE 2008         285  1.0     NaN  JAMJAM  10.78    0.190
                        2012         569  1.0  2197.0  JAMJAM  10.75    0.153
                        2016        1056  3.0   887.0  JAMJAM  10.86    0.138
Sherone SIMPSON         2004        1375  6.0     NaN  JAMJAM  11.07    0.164
                        2008         286  2.0     NaN  JAMJAM  10.98    0.155
Stanislavs OLIJARS      2004        1688  5.0     NaN  LATLAT  13.21    0.174
Tayna LAWRENCE          2000        1989  2.0     NaN  JAMJAM  11.18    0.163
Terrence TRAMMELL       2000        2092  2.0     NaN  USAUSA  13.16    0.221
                        2004        1685  2.0     NaN  USAUSA  13.18    0.154
Tianna BARTOLETTA       2012         572  4.0  3306.0  USAUSA  10.85    0.171
Tiffany PORTER          2016         868  7.0   719.0     GBR  12.76    0.142
Tori BOWIE              2016        1055  2.0  1326.0  USAUSA  10.83    0.112
Torri EDWARDS           2008         292  8.0     NaN  USAUSA   11.2    0.179
Trayvon BROMELL         2016        1185  8.0  3054.0  USAUSA  10.06    0.135
Tyson GAY               2012         693  NaN  3217.0  USAUSA     DQ    0.145
Usain BOLT              2008         136  1.0     NaN  JAMJAM   9.69    0.165
                        2012         686  1.0  2170.0  JAMJAM   9.63    0.165
                        2016        1178  1.0  2612.0  JAMJAM   9.81    0.155
Veronica CAMPBELL-BROWN 2004        1372  3.0     NaN  JAMJAM  10.97    0.199
                        2012         571  3.0  2194.0  JAMJAM  10.81    0.143
Walter DIX              2008         138  3.0     NaN  USAUSA   9.91    0.133
Xiang LIU               2004        1684  1.0     NaN  CHNCHN  12.91    0.139
Yohan BLAKE             2012         687  2.0  2169.0  JAMJAM   9.75    0.179
                        2016        1181  4.0  2611.0  JAMJAM   9.93    0.145
Yuliya NESTSIARENKA     2004        1370  1.0     NaN  BLRBLR  10.93    0.186
Zhanna BLOCK            2000        1991  4.0     NaN  UKRUKR   11.2    0.223

                                 Race  Round Gender
ATHLETE                 Year
Akani SIMBINE           2016    100 m  Final      M
Aleen BAILEY            2004    100 m  Final      F
Aliuska LÓPEZ           2000  100 m H  Final      F
Allen JOHNSON           2000  110 m H  Final      M
Allyson FELIX           2012    100 m  Final      F
Andre DE GRASSE         2016    100 m  Final      M
Angela WHYTE            2004  100 m H  Final      F
Anier GARCÍA            2000  110 m H  Final      M
                        2004  110 m H  Final      M
Aries MERRITT           2012  110 m H  Final      M
Artur NOGA              2008  110 m H  Final      M
Asafa POWELL            2004    100 m  Final      M
                        2008    100 m  Final      M
                        2012    100 m  Final      M
Ato BOLDON              2000    100 m  Final      M
Aziz ZAKARI             2000    100 m  Final      M
                        2004    100 m  Final      M
Beate SCHROTT           2012  100 m H  Final      F
Ben Youssef MEITÉ       2016    100 m  Final      M
Blessing OKAGBARE       2012    100 m  Final      F
Brianna ROLLINS         2016  100 m H  Final      F
Brigitte FOSTER-HYLTON  2000  100 m H  Final      F
                        2008  100 m H  Final      F
Carmelita JETER         2012    100 m  Final      F
Chandra STURRUP         2000    100 m  Final      F
Charles ALLEN           2004  110 m H  Final      M
Christania WILLIAMS     2016    100 m  Final      F
Churandy MARTINA        2008    100 m  Final      M
                        2012    100 m  Final      M
Cindy OFILI             2016  100 m H  Final      F
...                               ...    ...    ...
Sally PEARSON           2012  100 m H  Final      F
Sarah CLAXTON           2008  100 m H  Final      F
Savatheda FYNES         2000    100 m  Final      F
Shawn CRAWFORD          2004    100 m  Final      M
Shelly-Ann FRASER-PRYCE 2008    100 m  Final      F
                        2012    100 m  Final      F
                        2016    100 m  Final      F
Sherone SIMPSON         2004    100 m  Final      F
                        2008    100 m  Final      F
Stanislavs OLIJARS      2004  110 m H  Final      M
Tayna LAWRENCE          2000    100 m  Final      F
Terrence TRAMMELL       2000  110 m H  Final      M
                        2004  110 m H  Final      M
Tianna BARTOLETTA       2012    100 m  Final      F
Tiffany PORTER          2016  100 m H  Final      F
Tori BOWIE              2016    100 m  Final      F
Torri EDWARDS           2008    100 m  Final      F
Trayvon BROMELL         2016    100 m  Final      M
Tyson GAY               2012    100 m  Final      M
Usain BOLT              2008    100 m  Final      M
                        2012    100 m  Final      M
                        2016    100 m  Final      M
Veronica CAMPBELL-BROWN 2004    100 m  Final      F
                        2012    100 m  Final      F
Walter DIX              2008    100 m  Final      M
Xiang LIU               2004  110 m H  Final      M
Yohan BLAKE             2012    100 m  Final      M
                        2016    100 m  Final      M
Yuliya NESTSIARENKA     2004    100 m  Final      F
Zhanna BLOCK            2000    100 m  Final      F

[160 rows x 9 columns]

17) Now use the above, plus chaining with `.loc[]` and `max()` to find Usain Bolt's *worst* reaction time in an Olympics final.

In [0]:
# Fill in your answer to 17 here
df[df['Round']=='Final'].loc['Usain BOLT','RxnTime'].max()

0.165

18) Let's clean up this data a little bit more.  See all the `NaN` values above?  Those correspond to missing data (NaN stands for "Not a Number").  We can get rid of rows that have missing data with the `.dropna()` method.  But some missing data is irrelevant to our analysis.  Who cares if the bib number is missing?  Select only those columns we care about (let's say reaction time, round, and gender) using the approach from question 6, and then use `dropna()` on that subset of the columns.  Chain that with `.shape` to see how many rows the remaining data has.  It should be less than the number of rows we started with (because we removed some rows), but still well more than 0!

In [0]:
# Fill in your answer to 18 here
df[['RxnTime','Round','Gender']].dropna().shape

(2123, 3)

19) Do Americans sprinters react faster than Canadian sprinters?  No one would ever fund such a study, but you can answer that question right here for free!  Use the `.groupby()` method to aggregate sprinters by country `.groupby('COUNTRY')`, select the reaction time column, and chain it with `.mean()` to compare mean reaction time across countries.  You can further optionally append `[['USAUSA','CANCAN']]` to focus on only those two countries.  Why are all the country names doubled?  I think it is because the person who compiled this dataset likes to say, "U-S-A!  U-S-A!" and just repeated that for every country.

In [0]:
# Fill in your answer to 19 here
df.groupby('COUNTRY')['RxnTime'].mean()[['USAUSA','CANCAN']]

COUNTRY
USAUSA    0.170185
CANCAN    0.159889
Name: RxnTime, dtype: float64

In [0]:
# Be sure to run this code cell!
from scipy.stats import ttest_ind

20) So *do* Americans react faster (or slower) than Canadians? In the previous question we only computed the means.  What about the variability?  Let's assume for the moment that a t-test is a good way to compare the two groups.  Extract the two groups using the data using the selector approach from question 16, extract the reaction time from each, drop the missing values, and assigning one to the variable `usa` and the other to the variable `can`.  Don't use `groupby()` here.  Having loaded a t-test function (`ttest_ind` in the cell above), call that function using your selected groups (`ttest_ind(usa,can)`).  Note that you can have multiple command in a code cell, as long each one is on its own line.

In [0]:
# Fill in your answer to 20 here
usa = df[df['COUNTRY'] == 'USAUSA']
usa = usa['RxnTime'].dropna()
can = df[df['COUNTRY'] == 'CANCAN']
can = can['RxnTime'].dropna()
ttest_ind(usa, can)

Ttest_indResult(statistic=2.627641765259621, pvalue=0.009140575516656623)

21) Oh my, are we going to win a Nobel Prize for this discovery?  Or have we failed to control for something?  Maybe one country has more male vs female athletes, or more sprinters vs hurdlers.  Repeat the above, restricting the data to men (21a), then to women (21b), then to only 100 m sprinters (21c).  You can have multiple `==` expressions in your selector, but you should use parentheses to keep them separated e.g. `(df['COUNTRY']=='USA') & (df['Gender']=='F')`.

In [0]:
# Fill in your answer to 21a here
usa = df[(df['COUNTRY'] == 'USAUSA') & (df['Gender'] == 'M')]['RxnTime'].dropna()
can = df[(df['COUNTRY'] == 'CANCAN') & (df['Gender'] == 'M')]['RxnTime'].dropna()
ttest_ind(usa, can)

Ttest_indResult(statistic=2.0779762126756274, pvalue=0.0397416990780365)

In [0]:
# Fill in your answer to 21b here
usa = df[(df['COUNTRY'] == 'USAUSA') & (df['Gender'] == 'F')]['RxnTime'].dropna()
can = df[(df['COUNTRY'] == 'CANCAN') & (df['Gender'] == 'F')]['RxnTime'].dropna()
ttest_ind(usa, can)

Ttest_indResult(statistic=1.80019192856523, pvalue=0.074407006123811)

In [0]:
# Fill in your answer to 21c here
usa = df[(df['COUNTRY'] == 'USAUSA') & (df['Race'] == '100m')]['RxnTime'].dropna()
can = df[(df['COUNTRY'] == 'CANCAN') & (df['Race'] == '100m')]['RxnTime'].dropna()
ttest_ind(usa, can)

Ttest_indResult(statistic=nan, pvalue=nan)

### Congratulations, you are now familiar with the basic of programmatic operations on structured data!